"""
app.py  (updated)
-----------------
Streamlit UI with two task panels:
  - Rule-Based Tasks  (deterministic, from rules.py)
  - LLM-Suggested Tasks  (pattern-driven, from llm_suggest.py)
"""

import streamlit as st
import json
import subprocess

CONV_FILE = "conversation.json"
TASK_FILE = "task.json"


def add_record(text: str):
    with open(CONV_FILE, "r") as f:
        data = json.load(f)
    convo = data["Conversation"]
    new_id = str(len(convo) + 1)
    convo[new_id] = text
    with open(CONV_FILE, "w") as f:
        json.dump(data, f, indent=4)


def run_pipeline():
    subprocess.run(["python", "write_attr.py"], check=True)
    subprocess.run(["python", "generate_task.py"], check=True)


def load_tasks() -> dict:
    with open(TASK_FILE, "r") as f:
        return json.load(f)


# ── UI ─────────────────────────────────────────────────────────────────────────

st.set_page_config(page_title="LLM Planner", page_icon="🧠", layout="wide")
st.title("🧠 LLM Planner")
st.caption(
    "Rule-based exploitation **+** LLM pattern-recognition for personalised task suggestions."
)

# Input section
st.subheader("💬 New Conversation Record")
record = st.text_area(
    "Enter what the user said (health update, lifestyle note, etc.)",
    placeholder="e.g. 'I slept only 5 hours again last night and my back has been hurting for a week.'",
    height=100,
)

if st.button("➕ Add Record & Generate Tasks", type="primary"):
    if record.strip():
        with st.spinner("Extracting profile attributes..."):
            add_record(record.strip())
            run_pipeline()
        st.success("Pipeline complete — tasks updated below.")
        st.rerun()
    else:
        st.warning("Record cannot be empty.")

st.divider()

# Task display
tasks = load_tasks()

rule_tasks = {k: v for k, v in tasks.items() if not v.startswith("[LLM]")}
llm_tasks  = {k: v for k, v in tasks.items() if v.startswith("[LLM]")}

col1, col2 = st.columns(2)

with col1:
    st.subheader("📋 Rule-Based Tasks")
    st.caption("Generated by deterministic health rules.")
    if rule_tasks:
        for k, v in rule_tasks.items():
            st.markdown(f"**{k}.** {v}")
    else:
        st.info("No rule-based tasks yet. Add a conversation record to get started.")

with col2:
    st.subheader("✨ LLM-Suggested Tasks")
    st.caption("Pattern-detected by Groq LLM across conversation history and state transitions.")
    if llm_tasks:
        for k, v in llm_tasks.items():
            label = v.removeprefix("[LLM] ")
            st.markdown(f"**{k}.** {label}")
    else:
        st.info(
            "No LLM suggestions yet. The model needs at least one conversation "
            "record to identify patterns."
        )

# Sidebar: persona snapshot + history
st.sidebar.header("👤 Current Persona")
try:
    with open("persona.json", "r") as f:
        persona = json.load(f)
    for attr, val in persona.items():
        icon = "✅" if val not in (-1, None, "") else "❓"
        st.sidebar.markdown(f"{icon} **{attr}**: `{val}`")
except FileNotFoundError:
    st.sidebar.warning("persona.json not found.")

st.sidebar.divider()
st.sidebar.header("🕑 Persona History")
try:
    with open("persona_history.json", "r") as f:
        history = json.load(f)
    st.sidebar.caption(f"{len(history)} snapshot(s) recorded.")
    if history:
        latest = history[-1]
        st.sidebar.caption(f"Last updated: {latest.get('__timestamp__', 'unknown')}")
except FileNotFoundError:
    st.sidebar.info("No history yet.")